name: External API trigger test

on:
  repository_dispatch:
    types: [xray-test]

jobs:
  api-trigger-job:
    runs-on: ubuntu-latest

    steps:
      - name: Show payload
        run: |
          echo "Event triggered from external API"
          echo "Payload:"
          echo '${{ toJson(github.event.client_payload) }}'
